package smartspace.dao.rdb;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import smartspace.dao.ElementDao;
import smartspace.data.ElementEntity;

@Repository
public class RdbElementDao<ElementKey> implements ElementDao<ElementKey> {

	private ElementCrud elementCrud;
	private String smartspace;
	private String elementId;
	
	// TODO remove this
	private AtomicLong serial;

	@Autowired
	public RdbElementDao(ElementCrud elementCrud) {
		this.elementCrud = elementCrud;

		// TODO remove this
		this.serial = new AtomicLong(1000L);
	}

	@Value("${smartspace.name:smartspace}")
	public void setSmartspace(String smartspace) {
		this.smartspace = smartspace;
	}
	@Value("${elementId:0}")
	public void setElementId(String elementid) {
		this.elementId = elementid;
	}
	

	@Override
	@Transactional
	public ElementEntity create(ElementEntity element) {
		// TODO replace this with key generated by DB
		element.setKey(smartspace + "!" + elementId+ serial.getAndIncrement());
		
		// SQL: INSERT
		if (!this.elementCrud.existsById(element.getKey())) {
			return this.elementCrud.save(element);
		}else {
			throw new RuntimeException("message already exists with key: " + element.getKey());
		}
	}

	@Override
	@Transactional(readOnly=true)
	public List<ElementEntity> readAll() {
		List<ElementEntity> rv = new ArrayList<>();
		// SQL: SELECT
		this.elementCrud.findAll()
			.forEach(rv::add);
		return rv;
	}

	@Override
	@Transactional(readOnly=true)
	public Optional<ElementEntity> readById(ElementKey key) {
		// SQL: SELECT
		return this.elementCrud.findById((String)key);
	}

	@Override
	@Transactional
	public void update(ElementEntity update) {
		ElementEntity existing = 
				this.readById((ElementKey) update.getKey())
				.orElseThrow(()->new RuntimeException("no message entity with key: " + update.getKey()));
			
		if (update.getCreatorEmail() != null) {
			existing.setCreatorEmail(update.getCreatorEmail());
		}

		if (update.getMoreAttributes() != null) {
			existing.setMoreAttributes(update.getMoreAttributes());
		}
		
		if (update.getLocation()!=null) {
			existing.setLocation(update.getLocation());
		}
		
		if (update.getCreatorSmartspace()!=null) {
			existing.setCreatorSmartspace(update.getCreatorSmartspace());
		}
		if (update.getCreationTimestamp()!=null) {
			existing.setCreationTimestamp(update.getCreationTimestamp());
		}
		if (update.getElementId()!=null) {
			existing.setElementId(update.getElementId());
		}
		if (update.getName()!=null) {
			existing.setName(update.getName());
		}
		if (update.getType()!=null) {
			existing.setType(update.getType());
		}
		if (update.getElementSmartspace()!=null) {
			existing.setElementSmartspace(update.getElementSmartspace());
		}
	
		

		// SQL: UPDATE
		this.elementCrud.save(existing);
	}

	@Override
	@Transactional
	public void deleteAll() {
		// SQL: DELETE
		this.elementCrud.deleteAll();
	}

	@Override
	public void deleteByKey(ElementKey elementKey) {
		elementCrud.deleteById((String)elementKey);
		
	}

	@Override
	public void delete(ElementEntity elementEntity) {
		elementCrud.delete(elementEntity);
		
	}

}
